Ptt-official-app/go-pttbbs

.github/workflows/go.yml
adding coverage for easy reading (coverage by modules)
=> adding coverage.

api.go, api/load_general_articles.go, api/load_general_boards.go, api/testcases.go, apidoc/apidoc.py, apidoc/defs/article_summary.yaml, apidoc/defs/board_summary.yaml, apidoc/load_general_articles.yaml, apidoc/load_general_boards.yaml, apidoc/register.yaml, bbs/article_summary.go, bbs/board_summary.go, bbs/load_general_articles.go, bbs/testcases.go, cache/cache_board.go, cmsys/record.go, cmsys/record_test.go, go.mod, go.sum, main.go, ptt/article_list.go, ptt/article_list_test.go, ptttype/article_summary.go, test_index_test.go, test_load_general_articles_test.go, test_load_general_boards_test.go, test_login_test.go, test_util.go, test_util_test.go
1. add URL in ArticleSummary. 2. sync with official-doc
=> 1. add URL in ArticleSummary. 2. sync with official-doc

apidoc/template.yaml, docker-compose.yaml
1. add URL in ArticleSummary.
2. sync with official-doc
3. docker-compose use :3456, :8889, :48764
=> update version to 0.3.1

README.md, api/load_general_articles.go, api/load_general_articles_test.go, api/testcases.go, apidoc/defs/article_summary.yaml, apidoc/defs/board_summary.yaml, apidoc/load_general_articles.yaml, bbs/article_summary.go, bbs/board_summary.go, bbs/load_general_articles.go, bbs/load_general_articles_test.go, bbs/testcases.go, ptt/article_list.go, ptt/article_list_test.go
1. add is-newest in LoadGeneralArticles.
2. add BBoard in bbs.ArticleSummary.
=> LoadGeneralArticles.is-newest and bbs.ArticleSummary.BBoard.

README.md, api/auth_utils.go, api/auth_utils_test.go, api/login.go, api/register.go, api/types.go, apidoc/defs/article_summary.yaml, apidoc/defs/board_summary.yaml, apidoc/login.yaml, apidoc/me.yaml, apidoc/register.yaml, scripts/run.sh
no check of client-info in go-pttbbs.
client-info should be checked in middleware.
=> add client-info in jwt-token. 

api/auth_utils.go, api/change_passwd.go, api/change_passwd_test.go, api/login.go, api/register.go, bbs/change_passwd.go, bbs/change_passwd_test.go, bbs/get_user.go, bbs/login.go, cmbbs/passwd.go, cmbbs/passwd_test.go, main.go, ptt/cache.go, ptt/cache_test.go, ptt/user.go, ptt/user_test.go, test_change_passwd_test.go
1. api.ChangePasswd
2. use ptt.GetUser to get user-info (sync with money)
=> api.ChangePasswd

api/load_board_summary.go, api/load_board_summary_test.go, bbs/load_board_summary.go, bbs/load_board_summary_test.go, main.go, ptt/board_list.go, ptt/board_list_test.go, test_load_board_summary_test.go
- Add `boardsummary` in ptt board_list.go & bbs and api layer
- Register board summary endpoint in main.go
- TODO: Add unit test
=> Board summary api

api/get_article_test.go
Try to improve with a small step. 
- Test api.GetArticle
=> test api.GetArticle

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.9.10

scripts/rebuild_pttbbs.sh
To have openrestry work with term.devptt.site
=> whitelist in openrestry

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.9.11

Dockerfile, scripts/openrestry.sh, scripts/rebuild_pttbbs.sh
=> fix shm_offset and openrestry

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.9.12

api/load_auto_complete_boards.go, api/load_auto_complete_boards_test.go, bbs/load_auto_complete_boards.go, bbs/load_auto_complete_boards_test.go, bbs/load_general_boards_test.go, cache/cache_board.go, cache/cache_board_test.go, main.go, ptt/board_list.go, ptt/board_list_test.go, test_load_auto_complete_boards_test.go, types/cstr.go
=> api.LoadAutoCompleteBoards

apidoc/addsecurity.py, apidoc/apidoc.py, apidoc/load_auto_complete_boards.yaml, apidoc/parameters.py, apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template, scripts/swagger.sh
1. update version to 0.10.0
2. update apidoc to openapi3
3. update apidoc with api.LoadAutoCompleteBoards.
=> update version to 0.10.0

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.10.1

bbs/board_summary.go, cache/cache_board.go
=> remove unnecessary logs

.github/workflows/go.yml
add coverage report using codecov
=> add coverage report.

README.md
=> add badges in README.md

apidoc/apidoc.py, apidoc/create_board.yaml, apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.11.0

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.11.1

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.11.2

api/create_board_test.go, api/testcases_test.go, bbs/create_board.go
init BMs_userIDRaw in bbs.CreateBoard
=> (fix) init BMs_userIDRaw in bbs.CreateBoard

api/create_board_test.go, bbs/create_board_test.go
=> add wg in test

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.11.3

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.12.0

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.12.1

00-config.template.ini, 01-config.docker.ini
=> update default-guest as guest

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.12.2

Dockerfile, scripts/run.sh, types/types.go
實作 building time Git version tag 
https://github.com/Ptt-official-app/go-pttbbs/issues/139
=> Git tag version

api/api_utils.go
=> not-permitted as 403

apidoc/apidoc.py, apidoc/template.yaml, apidoc/version.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.12.3

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.12.4

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.12.5

00-config.template.ini, 01-config-docker.go.template, ptttype/00-config.go, scripts/docker_initbbs.sh, scripts/docker_tunepasswd.sh, scripts/rebuild_pttbbs.sh
update max-user as 200k in docker
=> update max-user as 200k in docker

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.12.6

01-config.docker.ini
shm-align-size as 4914304 (4MB)
=> shm-align-size as 4914304 (4MB)

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.12.7

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.12.8

api/reload_uhash.go, api/reload_uhash_test.go, bbs/reload_uhash.go, bbs/reload_uhash_test.go, initgin/init_gin.go, initgin/reload_uhash_test.go
=> reload-uhash

Dockerfile, apidoc/apidoc.py, apidoc/reload_uhash.yaml, scripts/docker_start.sh
=> reload-uhash add doc

apidoc/apidoc.py
=> reload-uhash doc

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.13.0

01-config-docker.go.template, api/set_user_perm.go, api/set_user_perm_test.go, bbs/set_user_perm.go, bbs/set_user_perm_test.go, initgin/init_gin.go, initgin/set_user_perm_test.go, initgin/testcases_test.go, ptt/user.go, ptt/user_test.go, scripts/rebuild_pttbbs.sh
=> set user perm

apidoc/apidoc.py, apidoc/set_user_perm.yaml, apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.13.1

scripts/rebuild_pttbbs.sh
=> max-board as 8192

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.13.2

bbs/bboard_id.go, bbs/bboard_id_test.go
=> allows '_' in board-id

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.13.3

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.14.0

01-config.docker.ini, ptttype/00-config.go
=> EDITPOST_SMARTMERGE as true

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.14.1

README.md, scripts/docker_initbbs.sh, scripts/docker_initpasswd.sh, scripts/docker_tunepasswd.sh
加上 docker_initpasswd 來 initialize /home/bbs/.PASSWORDS
#205
=> docker_initpasswd

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.14.2

bbs/article_summary.go, bbs/load_general_articles.go
SerializeArticleIdxStr and DeserializeArticleIdxStr as public method
=> SerializeArticleIdxStr and DeserializeArticleIdxStr as public method

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.14.3

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.14.4

initgin/attempt_change_email_test.go, initgin/attempt_set_id_email_test.go, initgin/change_email_test.go, initgin/change_passwd_test.go, initgin/check_exists_user_test.go, initgin/create_article_test.go, initgin/create_board_test.go, initgin/create_comment_test.go, initgin/get_article_test.go, initgin/get_email_token_info_test.go, initgin/get_favorites_test.go, initgin/get_token_info_test.go, initgin/get_user_test.go, initgin/index_test.go, initgin/is_board_valid_user_test.go, initgin/load_auto_complete_boards_test.go, initgin/load_board_summary_test.go, initgin/load_boards_by_bids_test.go, initgin/load_bottom_articles_test.go, initgin/load_general_articles_test.go, initgin/load_general_boards_by_class_test.go, initgin/load_general_boards_test.go, initgin/load_hot_boards_test.go, initgin/login_test.go, initgin/reload_uhash_test.go, initgin/set_id_email_test.go, initgin/set_user_perm_test.go, initgin/testcases_test.go
router as local-var in initgin test
=> router as local-var in initgin test

.github/workflows/go.yml
=> clean shm before go test

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.15.1

api/auth_utils.go
ParseJwt / ParseClaimString / ParseClaimInt as public functions
=> ParseJwt / ParseClaimString / ParseClaimInt as public functions

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.15.2

api/api_login_required.go, api/api_login_required_path.go
=> failed jwt as guest

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.15.3

cmsys/lock_test.go
=> file2 in lock-test

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.15.4

api/get_article.go, apidoc/get_article.yaml
get-article is with system-flag
=> get-article is with system-flag

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.15.5

apidoc/cross_post.yaml, apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.16.0

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.16.1

apidoc/defs/article_summary.yaml, apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.16.2

api/get_article.go, scripts/rebuild_pttbbs.sh
change to pmake in bbsdocker/imageptt:latest
=> change to pmake in bbsdocker/imageptt:latest

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.16.3

api/is_boards_valid_user.go, api/is_boards_valid_user_test.go, apidoc/apidoc.py, apidoc/is_board_valid_user.yaml, apidoc/is_boards_valid_user.yaml, bbs/bboard_id.go, bbs/is_boards_valid_user.go, bbs/is_boards_valid_user_test.go, initgin/init_gin.go, initgin/init_gin_test.go
=> api.IsBoardsValidUser

.gitignore, ptt/mbbsd.go, ptt/mbbsd_test.go, ptt/passwd.go, ptt/passwd_test.go
Update user numLoginDays, LastLogin and LastSeen
But the num increases 1 for every single day from 00:00
#250
=> [WIP] Issue 250

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.17.1

cache/cache_board_test.go, cache/cache_shm_test.go, cache/statistic_test.go, ptt/board_list.go
load-board-stat (used only by LoadBoardsByBids) includes foldes
#246
=> load-board-stat (used only by LoadBoardsByBids) includes foldes

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.17.2

api/load_board_detail.go, api/load_board_detail_test.go, api/testcases_test.go, bbs/board_detail.go, bbs/board_detail_test.go, bbs/load_board_detail.go, bbs/load_board_detail_test.go, bbs/testcases_test.go, initgin/init_gin.go, ptt/board_list.go
- Board detail api & unit test (不太確定帶入 bid 的方式對不對，在 review 內有留下一些問題)
https://github.com/Ptt-official-app/go-pttbbs/issues/37
=> Board detail api

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.18.0

api/edit_article.go, bbs/edit_article.go, bbs/edit_article_test.go, ptt/bbs.go, ptt/bbs_test.go
add posttype in api.EditArticle
=> add posttype in api.EditArticle

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.18.1

api/edit_article.go, api/edit_article_test.go, apidoc/edit_article.yaml, bbs/edit_article.go, bbs/edit_article_test.go, ptt/bbs.go, ptt/bbs_test.go
api.EditArticleResult add title and class
=> api.EditArticleResult add title and class

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.18.2

api/edit_article.go, api/edit_article_test.go, bbs/edit_article.go, bbs/edit_article_test.go
api.EditArticleResult add full_title
=> api.EditArticleResult add full_title

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.18.3

apidoc/apidoc.py, apidoc/delete_articles.yaml, apidoc/edit_article.yaml, apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.19.0

apidoc/delete_articles.yaml, apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.19.1

api/get_user_visit_count_test.go, apidoc/apidoc.py, apidoc/get_user_visit_count.yaml, apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template, initgin/init_gin_test.go
=> update version to 0.19.2

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.20.0

api/load_hot_boards_test.go, bbs/load_hot_boards.go, bbs/load_hot_boards_test.go
use ptt.load-hot-boards amid boardd is using utf8
=> use ptt.load-hot-boards amid boardd is using utf8

bbs/board_detail.go, bbs/board_summary.go, bbs/load_general_boards.go
serialize/deserialize board-idx as public function
=> serialize/deserialize board-idx as public function

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.20.2

scripts/rebuild_pttbbs.sh
add EXTENDED_INCHAR_ANSI (for boardd utf8)
=> add EXTENDED_INCHAR_ANSI

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.20.3

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
update version to 0.20.4
(to be indexed by sum.golang.org)
=> update version to 0.20.4

scripts/rebuild_pttbbs.sh
=> fix "#define"

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.21.0

mandreadarticle/errors.go, mandreadarticle/main.go, mandreadarticle/main_init.go
=> mandreadarticle

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.21.2

boarddreadcontent/main_init.go, mandloadmanarticles/main.go, mandloadmanarticles/main_init.go, mandreadarticle/main.go, mandreadarticle/main_init.go
=> fix boardd and mand clients

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.21.3

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.21.4

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.21.5

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.21.6

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.21.7

.github/workflows/go.yml
=> update go version to 1.19 in github-action

01-config-docker.go.template
=> update 01-config-docker to be aligned with production

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.21.9

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.21.10

.gitignore, ptttype/00-config-production.go, ptttype/02-config-run.go
=> add 00-config-production.go and 02-config-run.go to pttype

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.21.11

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update release to 0.21.12

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.21.13

README.en.md, README.zh-TW.md
=> new api doc website

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.22.0

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.23.0

bbs/board_detail.go
=> post-limit-bad-post

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.23.1

bbs/board_detail.go, ptttype/board_header_raw.go
=> PostExpire as Bid

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.23.2

.dockerignore, .gitignore, apidoc/apidoc.py, ptt/cache.go, ptt/mbbsd.go, ptttype/types.go
1. add more items in .dockerignore
2. add more items in .gitignore
3. fix _load_general_board_details in apidoc.py
4. always return uinfo in setupUtmp.
=> post-template: minor improvement

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.23.4

bbs/board_detail.go
=> bbs.BoardDetail.NUser from boardDetailRaw.NUser

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.23.5

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.23.6

api/write_favorites.go
=> params and path in api.WriteFavorites

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.23.8

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.24.0

ptt/comments.go
=> defensive programming for maxlen

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.24.1

apidoc/parameters.py
=> apidoc: check schema in params

api/auth_utils.go, api/change_passwd.go, api/change_passwd_test.go, api/get_refresh_token_info_test.go, api/get_token_info_test.go, api/login.go, api/refresh.go, api/refresh_test.go, api/register.go, apidoc/defs/token.yaml, apidoc/register.yaml, initgin/init_gin_test.go
=> expire-time when creating token

apidoc/template.yaml, docker-compose.yaml, docker-compose.yaml.template
=> update version to 0.24.2

apidoc/template.yaml, docker/go-pttbbs/docker-compose.yaml, docker/go-pttbbs/docker-compose.yaml.template
=> update version to 0.25.0

apidoc/template.yaml, docker/go-pttbbs/docker-compose.yaml, docker/go-pttbbs/docker-compose.yaml.template
=> update version to 0.25.1

apidoc/template.yaml, docker/go-pttbbs/docker-compose.yaml, docker/go-pttbbs/docker-compose.yaml.template
=> update version to 0.25.2

api/testinit_test.go, bbs/testinit_test.go, cmbbs/path/00-config.go, cmbbs/path/config.go, cmbbs/path/config_util.go, cmbbs/path/path.go, cmbbs/path/path_test.go, cmbbs/path/testinit.go, cmbbs/path/testinit_test.go, cmbbs/testinit_test.go, docs/config/config.ini.template, go-pttbbs/testinit_test.go, initgin/testinit_test.go, ptt/testinit_test.go, types/00-config.go
hack for possible duplicated board dir path from c-pttbbs.
=> Duplicated board dir path

apidoc/pyproject.toml, apidoc/template.yaml, docker/go-pttbbs/docker-compose.tmpl.yaml, docker/go-pttbbs/docker-compose.yaml
=> update version to 0.26.0

api/load_board_summary_all_guest.go, api/load_board_summary_all_guest_test.go, api/testcases_test.go, apidoc/apidoc.all_guest.py, apidoc/apidoc.full.py, bbs/bboard_id.go, bbs/load_board_summary_all_guest.go, cache/cache_board.go, initgin/init_gin.go
add LoadBoardSummaryAllGuest with return only `total` and `lastPosttime`
=> api.LoadBoardSummaryAllGuest

apidoc/pyproject.toml, apidoc/template.yaml, docker/go-pttbbs/docker-compose.tmpl.yaml
=> update version to 0.26.1

bbs/bboard_id.go
=> IS_ALL_GUEST for BBoardID.ToRaw and BBoardID.ToBrdname

apidoc/pyproject.toml, apidoc/template.yaml, docker/go-pttbbs/docker-compose.tmpl.yaml
=> update version to 0.26.2
